name: Called
on:
  push:
    branches: main
    
jobs:
  Execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Print some text
        run: |
          echo "Job1 is work"
          echo "Job2 is work"